openapi: 3.0.3
info:
  title: Ticket Booking API
  version: 1.0.0
  description: API para reservar tickets, integrando AWS SQS y S3.
servers:
  - url: http://localhost:8080
paths:
  /tickets:
    post:
      summary: Reservar un ticket
      description: |
        Reserva un ticket para un evento. Envía un mensaje a SQS y genera un archivo en S3 con los datos del ticket.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_email:
                  type: string
                  example: user@example.com
                event_id:
                  type: string
                  example: evt-123
              required:
                - user_email
                - event_id
      responses:
        '200':
          description: Ticket reservado con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Ticket reservado con éxito
                  ticket_id:
                    type: string
                    example: tkt-1681234567890
                  s3_key:
                    type: string
                    example: tickets/tkt-1681234567890.txt
        '400':
          description: Error de validación en la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Error interno (SQS o S3)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: string 